---

name: Make sure that a build of the project works.
on: push

jobs:
  pushchecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install prerequisites
        run: 'sudo apt-get install libreadline-dev'

      - name: Configure project
        run: ./configure

      - name: Run distcheck
        run: make distcheck
