---

name: Run code build tests
on:
  push:
    paths-ignore:
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        beagle: [--with-beagle, --without-beagle]
        mpi: [--with-mpi, --without-mpi]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Readline
        run: sudo apt install libreadline-dev

      - name: Install Beagle if needed
        if: ${{ matrix.beagle == '--with-beagle' }}
        run: sudo apt install libhmsbeagle-dev

      - name: Install MPI if needed
        if: ${{ matrix.mpi == '--with-mpi' }}
        run: sudo apt install libopenmpi-dev

      - name: Configure project
        run: ./configure --disable-doc ${{ matrix.mpi }} ${{ matrix.beagle }}

      - name: Build project
        run: make

      - name: Short test run (without MPI)
        if: ${{ matrix.mpi != '--with-mpi' }}
        run: cd examples && ../src/mb short-test.nex >test.out 2>test.err

      - name: Short test run (with MPI)
        if: ${{ matrix.mpi == '--with-mpi' }}
        run: cd examples && mpirun -np 2 ../src/mb short-test.nex >test.out 2>test.err

      - name: Error output should be empty
        run: test ! -s examples/test.err
