---

name: Run documentation build tests
on:
  push:
    paths-ignore:
      - 'src/**'

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install documentation prerequisites
        run: sudo apt-get install latexmk texlive-formats-extra

      - name: Configure project
        run: ./configure

      - name: Build project
        run: make pdf
